name: icon_animator
description: Simple and highly configurable icon resize animation with icon size, color, duration.
version: 0.0.2
homepage: https://github.com/thruthesky/icon_animator


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
